### PR TITLE
Made it working with PHP 8

### PR DESCRIPTION
**Pull request by markussoeth**
Patch for Issue #19

### CODE REVIEW

**Comment by FlashTVR** [comment]
Thank you very much @markussoeth! Have you tested to make sure it continue to work under PHP7 and older installations of PHPBB?

**Comment by markussoeth** [comment]
Tried to get rid of the php 7.1 Test error. Had 2 whitespaces in the code. sorry

**Comment by markussoeth** [comment]
It still worked for me under PHP 7 since the "foreach" function is available in PHP since PHP 4.
But I made a new pull request. Sorry, had two whitespace in the code. I changed that.

Testing with older phpbb installations I did not. 
First: the changes only effects the php behavior not the phpbb behavior.
Second: the people should upgrade their installation to actually versions, even for security reasons. Or use a older version of this extension. Also older phpbb installations would not run under php8 so no need to test it there.

**Comment by xchwarze** [comment]
@markussoeth @FlashTVR 

I haven't deployed this version in my server yet, but seeing the diff of the change, I was wondering if this is the right way to do it:
```
[$id, ] = array_shift($action);
```

**Comment by markussoeth** [comment]
> I haven't deployed this version in my server yet, but seeing the diff of the change, I was wondering if this is the right way to do it:
> 
> ```
> [$id, ] = array_shift($action);
> ```

I don't know. 
It works with the code I provided :-)
Give it a try and you will see.

But for me it seems to be a different between
each — Return the current key and value pair from an array and advance the array cursor
array_shift — Shift an element off the beginning of array

**Pull request merged**
